// Sort the timers on a 1 sec interval. Sorts the list based on most upcoming
sortTimers();

var bjora = {
    events: [
        {   // empty
            status: 0,
            key: 0,
        },

        {   // [1] Wisp
            status: 0,
            key: 0,
            cooldown: 60 * 9, 
            startButton: document.getElementById('timer-bjora-1-start'),
            startSideButton: document.getElementById('sidetimer-bjora-1-start'),
            resetButton: document.getElementById('timer-bjora-1-reset'),
            resetSideButton: document.getElementById('sidetimer-bjora-1-reset'),
            timeLabel: document.getElementById('timer-bjora-1'), 
            timeSideLabel: document.getElementById('sidetimer-bjora-1'),
            sidebox: document.getElementById('bjora-1-sidebox'),
            num: document.getElementById('numerical-sidetimer-bjora-1'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.num);},
        }, 
        {   // [2] Pineshade
            status: 0,
            key: 0,
            cooldown: 60 * 9, 
            startButton: document.getElementById('timer-bjora-2-start'),
            startSideButton: document.getElementById('sidetimer-bjora-2-start'),
            resetButton: document.getElementById('timer-bjora-2-reset'),
            resetSideButton: document.getElementById('sidetimer-bjora-2-reset'),
            timeLabel: document.getElementById('timer-bjora-2'), 
            timeSideLabel: document.getElementById('sidetimer-bjora-2'),
            sidebox: document.getElementById('bjora-2-sidebox'),
            num: document.getElementById('numerical-sidetimer-bjora-2'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.num);},
        },
        {   // [3] Bowman
            status: 0,
            key: 0,
            cooldown: 60 * 9, 
            startButton: document.getElementById('timer-bjora-3-start'),
            startSideButton: document.getElementById('sidetimer-bjora-3-start'),
            resetButton: document.getElementById('timer-bjora-3-reset'),
            resetSideButton: document.getElementById('sidetimer-bjora-3-reset'),
            timeLabel: document.getElementById('timer-bjora-3'), 
            timeSideLabel: document.getElementById('sidetimer-bjora-3'),
            sidebox: document.getElementById('bjora-3-sidebox'),
            num: document.getElementById('numerical-sidetimer-bjora-3'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.num);},
        },
        {   // [4] Murellow
            status: 0,
            key: 0,
            cooldown: 60 * 12 + 30, 
            startButton: document.getElementById('timer-bjora-4-start'),
            startSideButton: document.getElementById('sidetimer-bjora-4-start'),
            resetButton: document.getElementById('timer-bjora-4-reset'),
            resetSideButton: document.getElementById('sidetimer-bjora-4-reset'),
            timeLabel: document.getElementById('timer-bjora-4'), 
            timeSideLabel: document.getElementById('sidetimer-bjora-4'),
            sidebox: document.getElementById('bjora-4-sidebox'),
            num: document.getElementById('numerical-sidetimer-bjora-4'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.num);},
        },
        {   // [5] Skelk
            status: 0,
            key: 0,
            cooldown: 60 * 12 + 30, 
            startButton: document.getElementById('timer-bjora-5-start'),
            startSideButton: document.getElementById('sidetimer-bjora-5-start'),
            resetButton: document.getElementById('timer-bjora-5-reset'),
            resetSideButton: document.getElementById('sidetimer-bjora-5-reset'),
            timeLabel: document.getElementById('timer-bjora-5'), 
            timeSideLabel: document.getElementById('sidetimer-bjora-5'),
            sidebox: document.getElementById('bjora-5-sidebox'),
            num: document.getElementById('numerical-sidetimer-bjora-5'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.num);},
        },
        {   // [6] Berserker
            status: 0,
            key: 0,
            cooldown: 60 * 12 + 30, 
            startButton: document.getElementById('timer-bjora-6-start'),
            startSideButton: document.getElementById('sidetimer-bjora-6-start'),
            resetButton: document.getElementById('timer-bjora-6-reset'),
            resetSideButton: document.getElementById('sidetimer-bjora-6-reset'),
            timeLabel: document.getElementById('timer-bjora-6'), 
            timeSideLabel: document.getElementById('sidetimer-bjora-6'),
            sidebox: document.getElementById('bjora-6-sidebox'),
            num: document.getElementById('numerical-sidetimer-bjora-6'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.num);},
        },
        {   // [7] Shaman
            status: 0,
            key: 0,
            cooldown: 60 * 12 + 30, 
            startButton: document.getElementById('timer-bjora-7-start'),
            startSideButton: document.getElementById('sidetimer-bjora-7-start'),
            resetButton: document.getElementById('timer-bjora-7-reset'),
            resetSideButton: document.getElementById('sidetimer-bjora-7-reset'),
            timeLabel: document.getElementById('timer-bjora-7'), 
            timeSideLabel: document.getElementById('sidetimer-bjora-7'),
            sidebox: document.getElementById('bjora-7-sidebox'),
            num: document.getElementById('numerical-sidetimer-bjora-7'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.num);},
        },
        {   // [8] Brute
            status: 0,
            key: 0,
            cooldown: 60 * 12 + 30, 
            startButton: document.getElementById('timer-bjora-8-start'),
            startSideButton: document.getElementById('sidetimer-bjora-8-start'),
            resetButton: document.getElementById('timer-bjora-8-reset'),
            resetSideButton: document.getElementById('sidetimer-bjora-8-reset'),
            timeLabel: document.getElementById('timer-bjora-8'), 
            timeSideLabel: document.getElementById('sidetimer-bjora-8'),
            sidebox: document.getElementById('bjora-8-sidebox'),
            num: document.getElementById('numerical-sidetimer-bjora-8'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.num);},
        },
        {   // [9] Summoner
            status: 0,
            key: 0,
            cooldown: 60 * 12 + 30, 
            startButton: document.getElementById('timer-bjora-9-start'),
            startSideButton: document.getElementById('sidetimer-bjora-9-start'),
            resetButton: document.getElementById('timer-bjora-9-reset'),
            resetSideButton: document.getElementById('sidetimer-bjora-9-reset'),
            timeLabel: document.getElementById('timer-bjora-9'), 
            timeSideLabel: document.getElementById('sidetimer-bjora-9'),
            sidebox: document.getElementById('bjora-9-sidebox'),
            num: document.getElementById('numerical-sidetimer-bjora-9'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.num);},
        },
        {   // [10] Patrol NE
            status: 0,
            key: 0,
            cooldown: 60 * 6, 
            startButton: document.getElementById('timer-bjora-10-start'),
            startSideButton: document.getElementById('sidetimer-bjora-10-start'),
            resetButton: document.getElementById('timer-bjora-10-reset'),
            resetSideButton: document.getElementById('sidetimer-bjora-10-reset'),
            timeLabel: document.getElementById('timer-bjora-10'), 
            timeSideLabel: document.getElementById('sidetimer-bjora-10'),
            sidebox: document.getElementById('bjora-10-sidebox'),
            num: document.getElementById('numerical-sidetimer-bjora-10'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.num);},
        },
        {   // [11] Patrol N
            status: 0,
            key: 0,
            cooldown: 60 * 8, 
            startButton: document.getElementById('timer-bjora-11-start'),
            startSideButton: document.getElementById('sidetimer-bjora-11-start'),
            resetButton: document.getElementById('timer-bjora-11-reset'),
            resetSideButton: document.getElementById('sidetimer-bjora-11-reset'),
            timeLabel: document.getElementById('timer-bjora-11'), 
            timeSideLabel: document.getElementById('sidetimer-bjora-11'),
            sidebox: document.getElementById('bjora-11-sidebox'),
            num: document.getElementById('numerical-sidetimer-bjora-11'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.num);},
        },
        {   // [12] Patrol S
            status: 0,
            key: 0,
            cooldown: 60 * 6, 
            startButton: document.getElementById('timer-bjora-12-start'),
            startSideButton: document.getElementById('sidetimer-bjora-12-start'),
            resetButton: document.getElementById('timer-bjora-12-reset'),
            resetSideButton: document.getElementById('sidetimer-bjora-12-reset'),
            timeLabel: document.getElementById('timer-bjora-12'), 
            timeSideLabel: document.getElementById('sidetimer-bjora-12'),
            sidebox: document.getElementById('bjora-12-sidebox'),
            num: document.getElementById('numerical-sidetimer-bjora-12'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.num);},
        },
        {   // [13] Boneskinner
            status: 0,
            key: 0,
            cooldown: 60 * 5, 
            startButton: document.getElementById('timer-bjora-13-start'),
            startSideButton: document.getElementById('sidetimer-bjora-13-start'),
            resetButton: document.getElementById('timer-bjora-13-reset'),
            resetSideButton: document.getElementById('sidetimer-bjora-13-reset'),
            timeLabel: document.getElementById('timer-bjora-13'), 
            timeSideLabel: document.getElementById('sidetimer-bjora-13'),
            sidebox: document.getElementById('bjora-13-sidebox'),
            num: document.getElementById('numerical-sidetimer-bjora-13'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.num);},
        },

    ]
};
// Dynamically creates unique keys
add_event_keys(bjora.events); 