// Sort the timers on a 1 sec interval. Sorts the list based on most upcoming
sortTimers();

var drizzle= {
    events: [
        {   // empty
            status: 0,
            key: 0,
        },
        {   // [1] Vloxen Mine
            status: 0,
            key: 0,
            cooldown: 60 * 1, 
            startButton: document.getElementById('timer-drizzlewood-1-start'),
            startSideButton: document.getElementById('sidetimer-drizzlewood-1-start'),
            resetButton: document.getElementById('timer-drizzlewood-1-reset'),
            resetSideButton: document.getElementById('sidetimer-drizzlewood-1-reset'),
            timeLabel: document.getElementById('timer-drizzlewood-1'), 
            timeSideLabel: document.getElementById('sidetimer-drizzlewood-1'),
            textLabel: document.getElementById('timer-drizzlewood-1-text'),
            sidebox: document.getElementById('drizzlewood-1-sidebox'),
            num: document.getElementById('numerical-sidetimer-drizzlewood-1'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.num);},
        },
        {   // [2] Petraj Overlook
            status: 0,
            key: 0,
            cooldown: 60 * 1, 
            startButton: document.getElementById('timer-drizzlewood-2-start'),
            startSideButton: document.getElementById('sidetimer-drizzlewood-2-start'),
            resetButton: document.getElementById('timer-drizzlewood-2-reset'),
            resetSideButton: document.getElementById('sidetimer-drizzlewood-2-reset'),
            timeLabel: document.getElementById('timer-drizzlewood-2'), 
            timeSideLabel: document.getElementById('sidetimer-drizzlewood-2'),
            textLabel: document.getElementById('timer-drizzlewood-2-text'),
            sidebox: document.getElementById('drizzlewood-2-sidebox'),
            num: document.getElementById('numerical-sidetimer-drizzlewood-2'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.num);},
        },
        {   // [3] Fort Defiance
            status: 0,
            key: 0,
            cooldown: 60 * 1, 
            startButton: document.getElementById('timer-drizzlewood-3-start'),
            startSideButton: document.getElementById('sidetimer-drizzlewood-3-start'),
            resetButton: document.getElementById('timer-drizzlewood-3-reset'),
            resetSideButton: document.getElementById('sidetimer-drizzlewood-3-reset'),
            timeLabel: document.getElementById('timer-drizzlewood-3'), 
            timeSideLabel: document.getElementById('sidetimer-drizzlewood-3'),
            textLabel: document.getElementById('timer-drizzlewood-3-text'),
            sidebox: document.getElementById('drizzlewood-3-sidebox'),
            num: document.getElementById('numerical-sidetimer-drizzlewood-3'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.num);},
        },
        {   // [4] Port Cascadia
            status: 0,
            key: 0,
            cooldown: 60 * 1, 
            startButton: document.getElementById('timer-drizzlewood-4-start'),
            startSideButton: document.getElementById('sidetimer-drizzlewood-4-start'),
            resetButton: document.getElementById('timer-drizzlewood-4-reset'),
            resetSideButton: document.getElementById('sidetimer-drizzlewood-4-reset'),
            timeLabel: document.getElementById('timer-drizzlewood-4'), 
            timeSideLabel: document.getElementById('sidetimer-drizzlewood-4'),
            textLabel: document.getElementById('timer-drizzlewood-4-text'),
            sidebox: document.getElementById('drizzlewood-4-sidebox'),
            num: document.getElementById('numerical-sidetimer-drizzlewood-4'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.num);},
        },
        {   // [5] Leadfoot Village
            status: 0,
            key: 0,
            cooldown: 60 * 1, 
            startButton: document.getElementById('timer-drizzlewood-5-start'),
            startSideButton: document.getElementById('sidetimer-drizzlewood-5-start'),
            resetButton: document.getElementById('timer-drizzlewood-5-reset'),
            resetSideButton: document.getElementById('sidetimer-drizzlewood-5-reset'),
            timeLabel: document.getElementById('timer-drizzlewood-5'), 
            timeSideLabel: document.getElementById('sidetimer-drizzlewood-5'),
            textLabel: document.getElementById('timer-drizzlewood-5-text'),
            sidebox: document.getElementById('drizzlewood-5-sidebox'),
            num: document.getElementById('numerical-sidetimer-drizzlewood-5'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.num);},
        },
        {   // [6] Lighthouse Point
            status: 0,
            key: 0,
            cooldown: 60 * 1, 
            startButton: document.getElementById('timer-drizzlewood-6-start'),
            startSideButton: document.getElementById('sidetimer-drizzlewood-6-start'),
            resetButton: document.getElementById('timer-drizzlewood-6-reset'),
            resetSideButton: document.getElementById('sidetimer-drizzlewood-6-reset'),
            timeLabel: document.getElementById('timer-drizzlewood-6'), 
            timeSideLabel: document.getElementById('sidetimer-drizzlewood-6'),
            textLabel: document.getElementById('timer-drizzlewood-6-text'),
            sidebox: document.getElementById('drizzlewood-6-sidebox'),
            num: document.getElementById('numerical-sidetimer-drizzlewood-6'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.num);},
        },
    ]
};
// Dynamically creates unique keys
add_event_keys(drizzle.events);
 

