// Sort the timers on a 1 sec interval. Sorts the list based on most upcoming
sortTimers();

let echovald = {
    events: [
        {   // Meta
            status: 0,
            key: 0,
            timeSideLabel: document.getElementById('sidetimer-echovald-meta'),
            sidebox: document.getElementById('echovald-meta-sidebox'),
            countdownSec: document.getElementById('numerical-sidetimer-echovald-meta')
        },
        {   // [1] N Spirits
            status: 0,
            key: 0,
            cooldown: 60 * 15, 
            startButton: document.getElementById('timer-echovald-1-start'),
            startSideButton: document.getElementById('sidetimer-echovald-1-start'),
            resetButton: document.getElementById('timer-echovald-1-reset'),
            resetSideButton: document.getElementById('sidetimer-echovald-1-reset'),
            timeLabel: document.getElementById('timer-echovald-1'), 
            timeSideLabel: document.getElementById('sidetimer-echovald-1'),
            sidebox: document.getElementById('echovald-1-sidebox'),
            countdownSec: document.getElementById('numerical-sidetimer-echovald-1'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.countdownSec);},
        },
        {   // [2] S Spirits
            status: 0,
            key: 0,
            cooldown: 60 * 15, 
            startButton: document.getElementById('timer-echovald-2-start'),
            startSideButton: document.getElementById('sidetimer-echovald-2-start'),
            resetButton: document.getElementById('timer-echovald-2-reset'),
            resetSideButton: document.getElementById('sidetimer-echovald-2-reset'),
            timeLabel: document.getElementById('timer-echovald-2'), 
            timeSideLabel: document.getElementById('sidetimer-echovald-2'),
            sidebox: document.getElementById('echovald-2-sidebox'),
            countdownSec: document.getElementById('numerical-sidetimer-echovald-2'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.countdownSec);},
        },
        {   // [3] NE Spirits
            status: 0,
            key: 0,
            cooldown: 60 * 15, 
            startButton: document.getElementById('timer-echovald-3-start'),
            startSideButton: document.getElementById('sidetimer-echovald-3-start'),
            resetButton: document.getElementById('timer-echovald-3-reset'),
            resetSideButton: document.getElementById('sidetimer-echovald-3-reset'),
            timeLabel: document.getElementById('timer-echovald-3'), 
            timeSideLabel: document.getElementById('sidetimer-echovald-3'),
            sidebox: document.getElementById('echovald-3-sidebox'),
            countdownSec: document.getElementById('numerical-sidetimer-echovald-3'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.countdownSec);},
        },
        {   // [4] Champ IGO
            status: 0,
            key: 0,
            cooldown: 60 * 13 + 30, 
            startButton: document.getElementById('timer-echovald-4-start'),
            startSideButton: document.getElementById('sidetimer-echovald-4-start'),
            resetButton: document.getElementById('timer-echovald-4-reset'),
            resetSideButton: document.getElementById('sidetimer-echovald-4-reset'),
            timeLabel: document.getElementById('timer-echovald-4'), 
            timeSideLabel: document.getElementById('sidetimer-echovald-4'),
            sidebox: document.getElementById('echovald-4-sidebox'),
            countdownSec: document.getElementById('numerical-sidetimer-echovald-4'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.countdownSec);},
        },
        {   // [5] Tomiko Escort
            status: 0,
            key: 0,
            cooldown: 60 * 11 + 45, 
            startButton: document.getElementById('timer-echovald-5-start'),
            startSideButton: document.getElementById('sidetimer-echovald-5-start'),
            resetButton: document.getElementById('timer-echovald-5-reset'),
            resetSideButton: document.getElementById('sidetimer-echovald-5-reset'),
            timeLabel: document.getElementById('timer-echovald-5'), 
            timeSideLabel: document.getElementById('sidetimer-echovald-5'),
            sidebox: document.getElementById('echovald-5-sidebox'),
            countdownSec: document.getElementById('numerical-sidetimer-echovald-5'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.countdownSec);},
        },
        {   // [6] Qinkai Chain
            status: 0,
            key: 0,
            cooldown: 60 * 11, 
            startButton: document.getElementById('timer-echovald-6-start'),
            startSideButton: document.getElementById('sidetimer-echovald-6-start'),
            resetButton: document.getElementById('timer-echovald-6-reset'),
            resetSideButton: document.getElementById('sidetimer-echovald-6-reset'),
            timeLabel: document.getElementById('timer-echovald-6'), 
            timeSideLabel: document.getElementById('sidetimer-echovald-6'),
            sidebox: document.getElementById('echovald-6-sidebox'),
            countdownSec: document.getElementById('numerical-sidetimer-echovald-6'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.countdownSec);},
        },
        {   // [7] Farmer Shi
            status: 0,
            key: 0,
            cooldown: 60 * 12 + 30, 
            startButton: document.getElementById('timer-echovald-7-start'),
            startSideButton: document.getElementById('sidetimer-echovald-7-start'),
            resetButton: document.getElementById('timer-echovald-7-reset'),
            resetSideButton: document.getElementById('sidetimer-echovald-7-reset'),
            timeLabel: document.getElementById('timer-echovald-7'), 
            timeSideLabel: document.getElementById('sidetimer-echovald-7'),
            sidebox: document.getElementById('echovald-7-sidebox'),
            countdownSec: document.getElementById('numerical-sidetimer-echovald-7'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.countdownSec);},
        },
        {   // [8] Grenadier
            status: 0,
            key: 0,
            cooldown: 60 * 13, 
            startButton: document.getElementById('timer-echovald-8-start'),
            startSideButton: document.getElementById('sidetimer-echovald-8-start'),
            resetButton: document.getElementById('timer-echovald-8-reset'),
            resetSideButton: document.getElementById('sidetimer-echovald-8-reset'),
            timeLabel: document.getElementById('timer-echovald-8'), 
            timeSideLabel: document.getElementById('sidetimer-echovald-8'),
            sidebox: document.getElementById('echovald-8-sidebox'),
            countdownSec: document.getElementById('numerical-sidetimer-echovald-8'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.countdownSec);},
        },
        {   // [9] Arborstone Defense
            status: 0,
            key: 0,
            cooldown: 60 * 12 + 15, 
            startButton: document.getElementById('timer-echovald-9-start'),
            startSideButton: document.getElementById('sidetimer-echovald-9-start'),
            resetButton: document.getElementById('timer-echovald-9-reset'),
            resetSideButton: document.getElementById('sidetimer-echovald-9-reset'),
            timeLabel: document.getElementById('timer-echovald-9'), 
            timeSideLabel: document.getElementById('sidetimer-echovald-9'),
            sidebox: document.getElementById('echovald-9-sidebox'),
            countdownSec: document.getElementById('numerical-sidetimer-echovald-9'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.countdownSec);},
        },
        {   // [10] Black Moa
            status: 0,
            key: 0,
            cooldown: 60 * 15 + 45, 
            startButton: document.getElementById('timer-echovald-10-start'),
            startSideButton: document.getElementById('sidetimer-echovald-10-start'),
            resetButton: document.getElementById('timer-echovald-10-reset'),
            resetSideButton: document.getElementById('sidetimer-echovald-10-reset'),
            timeLabel: document.getElementById('timer-echovald-10'), 
            timeSideLabel: document.getElementById('sidetimer-echovald-10'),
            sidebox: document.getElementById('echovald-10-sidebox'),
            countdownSec: document.getElementById('numerical-sidetimer-echovald-10'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.countdownSec);},
        },
        /*
        {   // [11] Enraged Kappa
            status: 0,
            key: 0,
            cooldown: 60 * 8 + 15, 
            startButton: document.getElementById('timer-echovald-11-start'),
            startSideButton: document.getElementById('sidetimer-echovald-11-start'),
            resetButton: document.getElementById('timer-echovald-11-reset'),
            resetSideButton: document.getElementById('sidetimer-echovald-11-reset'),
            timeLabel: document.getElementById('timer-echovald-11'), 
            timeSideLabel: document.getElementById('sidetimer-echovald-11'),
            sidebox: document.getElementById('echovald-11-sidebox'),
            countdownSec: document.getElementById('numerical-sidetimer-echovald-11'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.countdownSec);},
        },
        {   // [12] Shrine Guardian
            status: 0,
            key: 0,
            cooldown: 60 * 8 + 45, 
            startButton: document.getElementById('timer-echovald-12-start'),
            startSideButton: document.getElementById('sidetimer-echovald-12-start'),
            resetButton: document.getElementById('timer-echovald-12-reset'),
            resetSideButton: document.getElementById('sidetimer-echovald-12-reset'),
            timeLabel: document.getElementById('timer-echovald-12'), 
            timeSideLabel: document.getElementById('sidetimer-echovald-12'),
            sidebox: document.getElementById('echovald-12-sidebox'),
            countdownSec: document.getElementById('numerical-sidetimer-echovald-12'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.countdownSec);},
        },
        {   // [13] Speaker Outpost
            status: 0,
            key: 0,
            cooldown: 60 * 7, 
            startButton: document.getElementById('timer-echovald-13-start'),
            startSideButton: document.getElementById('sidetimer-echovald-13-start'),
            resetButton: document.getElementById('timer-echovald-13-reset'),
            resetSideButton: document.getElementById('sidetimer-echovald-13-reset'),
            timeLabel: document.getElementById('timer-echovald-13'), 
            timeSideLabel: document.getElementById('sidetimer-echovald-13'),
            sidebox: document.getElementById('echovald-13-sidebox'),
            countdownSec: document.getElementById('numerical-sidetimer-echovald-13'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.countdownSec);},
        },
        {   // [14] Speaker Champ
            status: 0,
            key: 0,
            cooldown: 60 * 7, 
            startButton: document.getElementById('timer-echovald-14-start'),
            startSideButton: document.getElementById('sidetimer-echovald-14-start'),
            resetButton: document.getElementById('timer-echovald-14-reset'),
            resetSideButton: document.getElementById('sidetimer-echovald-14-reset'),
            timeLabel: document.getElementById('timer-echovald-14'), 
            timeSideLabel: document.getElementById('sidetimer-echovald-14'),
            sidebox: document.getElementById('echovald-14-sidebox'),
            countdownSec: document.getElementById('numerical-sidetimer-echovald-14'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.countdownSec);},
        },
        {   // [15] Destroyer Void
            status: 0,
            key: 0,
            cooldown: 60 * 36 + 15, 
            startButton: document.getElementById('timer-echovald-15-start'),
            startSideButton: document.getElementById('sidetimer-echovald-15-start'),
            resetButton: document.getElementById('timer-echovald-15-reset'),
            resetSideButton: document.getElementById('sidetimer-echovald-15-reset'),
            timeLabel: document.getElementById('timer-echovald-15'), 
            timeSideLabel: document.getElementById('sidetimer-echovald-15'),
            sidebox: document.getElementById('echovald-15-sidebox'),
            countdownSec: document.getElementById('numerical-sidetimer-echovald-15'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.countdownSec);},
        },
        {   // [16] NW Void
            status: 0,
            key: 0,
            cooldown: 60 * 36 + 15, 
            startButton: document.getElementById('timer-echovald-16-start'),
            startSideButton: document.getElementById('sidetimer-echovald-16-start'),
            resetButton: document.getElementById('timer-echovald-16-reset'),
            resetSideButton: document.getElementById('sidetimer-echovald-16-reset'),
            timeLabel: document.getElementById('timer-echovald-16'), 
            timeSideLabel: document.getElementById('sidetimer-echovald-16'),
            sidebox: document.getElementById('echovald-16-sidebox'),
            countdownSec: document.getElementById('numerical-sidetimer-echovald-16'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.countdownSec);},
        },
        {   // [17] Brotherhood
            status: 0,
            key: 0,
            cooldown: 60 * 7 + 30, 
            startButton: document.getElementById('timer-echovald-17-start'),
            startSideButton: document.getElementById('sidetimer-echovald-17-start'),
            resetButton: document.getElementById('timer-echovald-17-reset'),
            resetSideButton: document.getElementById('sidetimer-echovald-17-reset'),
            timeLabel: document.getElementById('timer-echovald-17'), 
            timeSideLabel: document.getElementById('sidetimer-echovald-17'),
            sidebox: document.getElementById('echovald-17-sidebox'),
            countdownSec: document.getElementById('numerical-sidetimer-echovald-17'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.countdownSec);},
        },
        /*
        {   // [7] Volatile Sparks (Bori)
            status: 0,
            key: 0,
            cooldown: 60 * 34, 
            startButton: document.getElementById('timer-echovald-7-start'),
            startSideButton: document.getElementById('sidetimer-echovald-7-start'),
            resetButton: document.getElementById('timer-echovald-7-reset'),
            resetSideButton: document.getElementById('sidetimer-echovald-7-reset'),
            timeLabel: document.getElementById('timer-echovald-7'), 
            timeSideLabel: document.getElementById('sidetimer-echovald-7'),
            sidebox: document.getElementById('echovald-7-sidebox'),
            countdownSec: document.getElementById('numerical-sidetimer-echovald-7'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.countdownSec);},
        },
        */
    ]
};
// Dynamically creates unique keys
add_event_keys(echovald.events);
