// Sort the timers on a 1 sec interval. Sorts the list based on most upcoming
sortTimers();

let jahai = {
    events: [
        {   // empty
            status: 0,
            key: 0,
        },
        {   // [1] Yatendi Village
            status: 0,
            key: 0,
            cooldown: 60 * 23, 
            startButton: document.getElementById('timer-jahai-1-start'),
            startSideButton: document.getElementById('sidetimer-jahai-1-start'),
            resetButton: document.getElementById('timer-jahai-1-reset'),
            resetSideButton: document.getElementById('sidetimer-jahai-1-reset'),
            timeLabel: document.getElementById('timer-jahai-1'), 
            timeSideLabel: document.getElementById('sidetimer-jahai-1'),
            sidebox: document.getElementById('jahai-1-sidebox'),
            countdownSec: document.getElementById('numerical-sidetimer-jahai-1'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.countdownSec);},
        },
        {   // [2] Ziya
            status: 0,
            key: 0,
            cooldown: 60 * 13 + 45, 
            startButton: document.getElementById('timer-jahai-2-start'),
            startSideButton: document.getElementById('sidetimer-jahai-2-start'),
            resetButton: document.getElementById('timer-jahai-2-reset'),
            resetSideButton: document.getElementById('sidetimer-jahai-2-reset'),
            timeLabel: document.getElementById('timer-jahai-2'), 
            timeSideLabel: document.getElementById('sidetimer-jahai-2'),
            sidebox: document.getElementById('jahai-2-sidebox'),
            countdownSec: document.getElementById('numerical-sidetimer-jahai-2'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.countdownSec);},
        },
        {   // [3] Garrison Escort
            status: 0,
            key: 0,
            cooldown: 60 * 2 + 30, 
            startButton: document.getElementById('timer-jahai-3-start'),
            startSideButton: document.getElementById('sidetimer-jahai-3-start'),
            resetButton: document.getElementById('timer-jahai-3-reset'),
            resetSideButton: document.getElementById('sidetimer-jahai-3-reset'),
            timeLabel: document.getElementById('timer-jahai-3'), 
            timeSideLabel: document.getElementById('sidetimer-jahai-3'),
            sidebox: document.getElementById('jahai-3-sidebox'),
            countdownSec: document.getElementById('numerical-sidetimer-jahai-3'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.countdownSec);},
        },
        {   // [4] DERV
            status: 0,
            key: 0,
            cooldown: 60 * 14 + 45, 
            startButton: document.getElementById('timer-jahai-4-start'),
            startSideButton: document.getElementById('sidetimer-jahai-4-start'),
            resetButton: document.getElementById('timer-jahai-4-reset'),
            resetSideButton: document.getElementById('sidetimer-jahai-4-reset'),
            timeLabel: document.getElementById('timer-jahai-4'), 
            timeSideLabel: document.getElementById('sidetimer-jahai-4'),
            sidebox: document.getElementById('jahai-4-sidebox'),
            countdownSec: document.getElementById('numerical-sidetimer-jahai-4'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.countdownSec);},
        },
        {   // [5] Yatendi Village
            status: 0,
            key: 0,
            cooldown: 60 * 14, 
            startButton: document.getElementById('timer-jahai-5-start'),
            startSideButton: document.getElementById('sidetimer-jahai-5-start'),
            resetButton: document.getElementById('timer-jahai-5-reset'),
            resetSideButton: document.getElementById('sidetimer-jahai-5-reset'),
            timeLabel: document.getElementById('timer-jahai-5'), 
            timeSideLabel: document.getElementById('sidetimer-jahai-5'),
            sidebox: document.getElementById('jahai-5-sidebox'),
            countdownSec: document.getElementById('numerical-sidetimer-jahai-5'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.countdownSec);},
        },
        {   // [6] Chantry
            status: 0,
            key: 0,
            cooldown: 60 * 13, 
            startButton: document.getElementById('timer-jahai-6-start'),
            startSideButton: document.getElementById('sidetimer-jahai-6-start'),
            resetButton: document.getElementById('timer-jahai-6-reset'),
            resetSideButton: document.getElementById('sidetimer-jahai-6-reset'),
            timeLabel: document.getElementById('timer-jahai-6'), 
            timeSideLabel: document.getElementById('sidetimer-jahai-6'),
            sidebox: document.getElementById('jahai-6-sidebox'),
            countdownSec: document.getElementById('numerical-sidetimer-jahai-6'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.countdownSec);},
        },
        // START OF BOUNTIES
        {   // [7] LB: Wyverns 
            status: 0,
            key: 0,
            cooldown: 60 * 30, 
            startButton: document.getElementById('timer-jahai-7-start'),
            startSideButton: document.getElementById('sidetimer-jahai-7-start'),
            resetButton: document.getElementById('timer-jahai-7-reset'),
            resetSideButton: document.getElementById('sidetimer-jahai-7-reset'),
            timeLabel: document.getElementById('timer-jahai-7'), 
            timeSideLabel: document.getElementById('sidetimer-jahai-7'),
            sidebox: document.getElementById('jahai-7-sidebox'),
            countdownSec: document.getElementById('numerical-sidetimer-jahai-7'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.countdownSec);},
        },
        {   // [8] Ettin
            status: 0,
            key: 0,
            cooldown: 60 * 15, 
            startButton: document.getElementById('timer-jahai-8-start'),
            startSideButton: document.getElementById('sidetimer-jahai-8-start'),
            resetButton: document.getElementById('timer-jahai-8-reset'),
            resetSideButton: document.getElementById('sidetimer-jahai-8-reset'),
            timeLabel: document.getElementById('timer-jahai-8'), 
            timeSideLabel: document.getElementById('sidetimer-jahai-8'),
            sidebox: document.getElementById('jahai-8-sidebox'),
            countdownSec: document.getElementById('numerical-sidetimer-jahai-8'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.countdownSec);},
        },
        {   // [9] Pet Rock
            status: 0,
            key: 0,
            cooldown: 60 * 15, 
            startButton: document.getElementById('timer-jahai-9-start'),
            startSideButton: document.getElementById('sidetimer-jahai-9-start'),
            resetButton: document.getElementById('timer-jahai-9-reset'),
            resetSideButton: document.getElementById('sidetimer-jahai-9-reset'),
            timeLabel: document.getElementById('timer-jahai-9'), 
            timeSideLabel: document.getElementById('sidetimer-jahai-9'),
            sidebox: document.getElementById('jahai-9-sidebox'),
            countdownSec: document.getElementById('numerical-sidetimer-jahai-9'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.countdownSec);},
        },
        {   // [10] Weapons
            status: 0,
            key: 0,
            cooldown: 60 * 15, 
            startButton: document.getElementById('timer-jahai-10-start'),
            startSideButton: document.getElementById('sidetimer-jahai-10-start'),
            resetButton: document.getElementById('timer-jahai-10-reset'),
            resetSideButton: document.getElementById('sidetimer-jahai-10-reset'),
            timeLabel: document.getElementById('timer-jahai-10'), 
            timeSideLabel: document.getElementById('sidetimer-jahai-10'),
            sidebox: document.getElementById('jahai-10-sidebox'),
            countdownSec: document.getElementById('numerical-sidetimer-jahai-10'),
            doCountdown: function() {countdown(this.status, this.key, this.cooldown, this.timeLabel, this.timeSideLabel, this.sidebox, this.countdownSec);},
        },
    ]
};
// Dynamically creates unique keys
add_event_keys(jahai.events);